{{- if .Values.serviceAccounts.controller.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "scaleway-sfs-subdir-csi.controllerServiceAccount" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scaleway-sfs-subdir-csi.labels" . | nindent 4 }}
automountServiceAccountToken: true
---
{{- end }}
{{- if .Values.serviceAccounts.node.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "scaleway-sfs-subdir-csi.nodeServiceAccount" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scaleway-sfs-subdir-csi.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
